### ISSUE TITLE
Define a color for each branch

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edamontology#340]
Could we have a given color for each branch, in order to help visual people to easily understand what is the branch of the term their are going to read ?
Fixing it here in EDAM would allow each re-user of EDAM to use this color code, and have a coherent graphical environment.
It intend to use it in the [edam browser](https://github.com/IFB-ElixirFr/edam-browser)

Proposition of color:
[#FF8000](https://www.w3schools.com/colors/color_tryit.asp?hex=FF8000)
[#3ADF00](https://www.w3schools.com/colors/color_tryit.asp?hex=3ADF00)
[#00FFFF](https://www.w3schools.com/colors/color_tryit.asp?hex=00FFFF)
[#BE81F7](https://www.w3schools.com/colors/color_tryit.asp?hex=BE81F7)

**Comment by bryan-brancotte** [comment]
![image](https://user-images.githubusercontent.com/11556772/35870667-852eefb4-0b62-11e8-9307-5edfd6eba2e8.png)

**Comment by joncison** [comment]
Good idea and nice colours, although it would be worth researching conventional colour codes (if such a thing exists) for Web use.

**Comment by bryan-brancotte** [comment]
The colors proposed have been quickly and almost randomly chosen. Maybe using the four color of google/microsoft, if there is no patent.
After some research, when testing [here](http://www.color-blindness.com/coblis-color-blindness-simulator/) this color-set works with all Color Blindness peoples except Achromatopsia (only see in grey).

**Comment by bryan-brancotte** [comment]
![image](https://user-images.githubusercontent.com/11556772/35916329-5c56474c-0c0a-11e8-8b52-23afb5fafa44.png)

Which give
```css

.bg-edam-data-light{
    background-color:#d6b1c4;
}
.bg-edam-format-light{
    background-color:#9fb1d4;
}
.bg-edam-operation-light{
    background-color:#adcf9f;
}
.bg-edam-topic-light{
    background-color:#ffc6a7;
}
.bg-edam-data{
    background-color:#933162;
}
.bg-edam-format{
    background-color:#01308d;
}
.bg-edam-operation{
    background-color:#268101;
}
.bg-edam-topic{
    background-color:#fe6916;
}
.fg-edam-data{
    color:#933162;
}
.fg-edam-format{
    color:#01308d;
}
.fg-edam-operation{
    color:#268101;
}
.fg-edam-topic{
    color:#fe6916;
}
.fg-edam-deprecated{
    color:#999999;
}
```

**Comment by bryan-brancotte** [comment]
An example on how the color set is used :
https://ifb-elixirfr.github.io/edam-browser/#http://edamontology.org/operation_0337

**Comment by albangaignard** [comment]
Very nice work for the browser and the colors  ! 👍

**Comment by joncison** [comment]
This is very nice ... but I'd suggest that two red-ish colours are used for Data and Format  - given that these are conceptually close together, I think there colours should be, too.

So that would give:
* Operation (green)
* Topic (blue)
* Data (purple)
* Operation (red)

**Comment by bryan-brancotte** [comment]
Hi,
I forgot to mention that the color scheme in https://github.com/edamontology/edamontology/issues/340#issuecomment-363754915 comes from @hmenager, and probably a presentation.

**Comment by bryan-brancotte** [comment]
Hi @joncison, I think there is a typo in https://github.com/edamontology/edamontology/issues/340#issuecomment-364697703. For the color code, you mean : 
 - Operation (green)
 - Topic (blue)
 - Data (purple)
 - **Format** (red)

i.e exchanging color of topic and format ?

**Comment by joncison** [comment]
:) sorry, you're right.

**Comment by bryan-brancotte** [comment]
Hi @matuskalas could you change the color in the [EDAM relations figure](https://github.com/edamontology/edamontology/blob/master/EDAMrelations.png) to fit the scheme adjusted by @joncison ?
I can do a pull request with css, and colors, but I don't know where. Any idea ?

**Comment by bryan-brancotte** [comment]
Hi @joncison 
Following https://github.com/IFB-ElixirFr/edam-browser/issues/21 could you check if both background and foreground colors used in https://github.com/edamontology/edamontology/issues/340#issuecomment-363754915 are color-bind friendly enough ?

**Comment by joncison** [comment]
sorry, now in correct thread :)   The colours in edamontology/edamontology#340 (comment) look good!

**Comment by joncison** [comment]
Hi @bryan-brancotte, can we close this issue now?  

@matuskalas @hmenager @veitveit, please use the standard and now colour-perception-impaired-friendly scheme in future presentations?

**Comment by bryan-brancotte** [comment]
We can close it yes.
Where can we put the colors in the doc ? Maybe at https://github.com/edamontology/edamontologyDocs/blob/master/technical_details.rst ?
```css

.bg-edam-data-light{
    background-color:#d6b1c4;
}
.bg-edam-topic-light{
    background-color:#9fb1d4;
}
.bg-edam-operation-light{
    background-color:#adcf9f;
}
.bg-edam-format-light{
    background-color:#ffc6a7;
}
.bg-edam-data{
    background-color:#933162;
}
.bg-edam-topic{
    background-color:#01308d;
}
.bg-edam-operation{
    background-color:#268101;
}
.bg-edam-format{
    background-color:#fe6916;
}
.fg-edam-data{
    color:#933162;
}
.fg-edam-topic{
    color:#01308d;
}
.fg-edam-operation{
    color:#268101;
}
.fg-edam-format{
    color:#fe6916;
}
.fg-edam-deprecated{
    color:#999999;
}
```
